export const GAME_JOINED = 'GAME_JOINED';
export const GAME_CREATED = 'GAME_CREATED';
export const GAME_STARTED = 'GAME_STARTED';
export const GAME_PLAYER_ANSWERED = 'GAME_PLAYER_ANSWERED';
export const GAME_PLAYER_VOTED = 'GAME_PLAYER_VOTED';
export const GAME_ROUND_ENDED = 'GAME_ROUND_ENDED';
export const GAME_ENDED = 'GAME_ENDED';
export const GAME_CLOSED = 'GAME_CLOSED';
