module ActionTypes
    GAME_CREATED = "GAME_CREATED"
    GAME_JOINED = "GAME_JOINED"
    GAME_PLAYER_ANSWER = "GAME_PLAYER_ANSWER"
    GAME_PLAYER_VOTE = "GAME_PLAYER_VOTE"
    GAME_END = "GAME_END"
    GAME_ROOM_CLOSED = "GAME_ROOM_CLOSED"
end
  